//
// main_test.cpp for  in /home/atraxys/Workspace/Epitech/Year_2/cpp_indie_studio/src/Entity/
//
// Made by Philippe Lefevre
// Login   <philippe1.lefevre@epitech.eu>
//
// Started on  Wed Jun 14 05:13:36 2017 Philippe Lefevre
// Last update Fri Jun 16 02:26:07 2017 John Doe
//

#include "Game.hpp"

int	main(void)
{
        int _map[15][15] = {
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::NPC_TWO, indie::EntityType::BLOCK_EMPTY, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_EMPTY, indie::EntityType::PC_ONE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_EMPTY, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_EMPTY, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_EMPTY, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_EMPTY, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::NPC_TWO, indie::EntityType::BLOCK_EMPTY, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_DESTRUCTIBLE, indie::EntityType::BLOCK_EMPTY, indie::EntityType::NPC_THREE, indie::EntityType::BLOCK_INDESTRUCTIBLE },
                { indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE, indie::EntityType::BLOCK_INDESTRUCTIBLE }
        };


        Game bomberman(_map);

        bomberman.Play();
        return (0);
}
